export enum CepLogEvent {
  PROVIDER_FAILED = 'PROVIDER_FAILED',
  CEP_FOUND = 'CEP_FOUND',
  CEP_NOT_FOUND = 'CEP_NOT_FOUND',
  LOOKUP_EXHAUSTED = 'LOOKUP_EXHAUSTED',
  CIRCUIT_OPENED = 'CIRCUIT_OPENED',
  CIRCUIT_CLOSED = 'CIRCUIT_CLOSED',
}
